//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Club
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Book.
    /// </summary>
    // *** Start programmer edit section *** (Book CustomAttributes)

    // *** End programmer edit section *** (Book CustomAttributes)
    [AutoAltered()]
    [Caption("Книга")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BookE", new string[] {
            "Title as \'Название\'",
            "Author as \'Автор\'",
            "PagesCount as \'Количество страниц\'",
            "URLCover as \'Ссылка на обложку\'",
            "URLDescription as \'Ссылка на описание\'",
            "Tags as \'Тэги\'",
            "AverageCount as \'Средняя оценка\'"})]
    [View("BookL", new string[] {
            "Title as \'Название\'",
            "Author as \'Автор\'",
            "PagesCount as \'Количество страниц\'",
            "URLCover as \'Ссылка на обложку\'",
            "URLDescription as \'Ссылка на описание\'",
            "Tags as \'Тэги\'",
            "AverageCount as \'Средняя оценка\'"})]
    public class Book : ICSSoft.STORMNET.DataObject
    {
        
        private string fTitle;
        
        private string fAuthor;
        
        private int fPagesCount;
        
        private string fURLCover;
        
        private string fURLDescription;
        
        private string fTags;
        
        private double fAverageCount;
        
        // *** Start programmer edit section *** (Book CustomMembers)

        // *** End programmer edit section *** (Book CustomMembers)

        
        /// <summary>
        /// Title.
        /// </summary>
        // *** Start programmer edit section *** (Book.Title CustomAttributes)

        // *** End programmer edit section *** (Book.Title CustomAttributes)
        [StrLen(255)]
        public virtual string Title
        {
            get
            {
                // *** Start programmer edit section *** (Book.Title Get start)

                // *** End programmer edit section *** (Book.Title Get start)
                string result = this.fTitle;
                // *** Start programmer edit section *** (Book.Title Get end)

                // *** End programmer edit section *** (Book.Title Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.Title Set start)

                // *** End programmer edit section *** (Book.Title Set start)
                this.fTitle = value;
                // *** Start programmer edit section *** (Book.Title Set end)

                // *** End programmer edit section *** (Book.Title Set end)
            }
        }
        
        /// <summary>
        /// Author.
        /// </summary>
        // *** Start programmer edit section *** (Book.Author CustomAttributes)

        // *** End programmer edit section *** (Book.Author CustomAttributes)
        [StrLen(255)]
        public virtual string Author
        {
            get
            {
                // *** Start programmer edit section *** (Book.Author Get start)

                // *** End programmer edit section *** (Book.Author Get start)
                string result = this.fAuthor;
                // *** Start programmer edit section *** (Book.Author Get end)

                // *** End programmer edit section *** (Book.Author Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.Author Set start)

                // *** End programmer edit section *** (Book.Author Set start)
                this.fAuthor = value;
                // *** Start programmer edit section *** (Book.Author Set end)

                // *** End programmer edit section *** (Book.Author Set end)
            }
        }
        
        /// <summary>
        /// PagesCount.
        /// </summary>
        // *** Start programmer edit section *** (Book.PagesCount CustomAttributes)

        // *** End programmer edit section *** (Book.PagesCount CustomAttributes)
        public virtual int PagesCount
        {
            get
            {
                // *** Start programmer edit section *** (Book.PagesCount Get start)

                // *** End programmer edit section *** (Book.PagesCount Get start)
                int result = this.fPagesCount;
                // *** Start programmer edit section *** (Book.PagesCount Get end)

                // *** End programmer edit section *** (Book.PagesCount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.PagesCount Set start)

                // *** End programmer edit section *** (Book.PagesCount Set start)
                this.fPagesCount = value;
                // *** Start programmer edit section *** (Book.PagesCount Set end)

                // *** End programmer edit section *** (Book.PagesCount Set end)
            }
        }
        
        /// <summary>
        /// URLCover.
        /// </summary>
        // *** Start programmer edit section *** (Book.URLCover CustomAttributes)

        // *** End programmer edit section *** (Book.URLCover CustomAttributes)
        [StrLen(255)]
        public virtual string URLCover
        {
            get
            {
                // *** Start programmer edit section *** (Book.URLCover Get start)

                // *** End programmer edit section *** (Book.URLCover Get start)
                string result = this.fURLCover;
                // *** Start programmer edit section *** (Book.URLCover Get end)

                // *** End programmer edit section *** (Book.URLCover Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.URLCover Set start)

                // *** End programmer edit section *** (Book.URLCover Set start)
                this.fURLCover = value;
                // *** Start programmer edit section *** (Book.URLCover Set end)

                // *** End programmer edit section *** (Book.URLCover Set end)
            }
        }
        
        /// <summary>
        /// URLDescription.
        /// </summary>
        // *** Start programmer edit section *** (Book.URLDescription CustomAttributes)

        // *** End programmer edit section *** (Book.URLDescription CustomAttributes)
        [StrLen(255)]
        public virtual string URLDescription
        {
            get
            {
                // *** Start programmer edit section *** (Book.URLDescription Get start)

                // *** End programmer edit section *** (Book.URLDescription Get start)
                string result = this.fURLDescription;
                // *** Start programmer edit section *** (Book.URLDescription Get end)

                // *** End programmer edit section *** (Book.URLDescription Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.URLDescription Set start)

                // *** End programmer edit section *** (Book.URLDescription Set start)
                this.fURLDescription = value;
                // *** Start programmer edit section *** (Book.URLDescription Set end)

                // *** End programmer edit section *** (Book.URLDescription Set end)
            }
        }
        
        /// <summary>
        /// Tags.
        /// </summary>
        // *** Start programmer edit section *** (Book.Tags CustomAttributes)

        // *** End programmer edit section *** (Book.Tags CustomAttributes)
        [StrLen(255)]
        public virtual string Tags
        {
            get
            {
                // *** Start programmer edit section *** (Book.Tags Get start)

                // *** End programmer edit section *** (Book.Tags Get start)
                string result = this.fTags;
                // *** Start programmer edit section *** (Book.Tags Get end)

                // *** End programmer edit section *** (Book.Tags Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.Tags Set start)

                // *** End programmer edit section *** (Book.Tags Set start)
                this.fTags = value;
                // *** Start programmer edit section *** (Book.Tags Set end)

                // *** End programmer edit section *** (Book.Tags Set end)
            }
        }
        
        /// <summary>
        /// AverageCount.
        /// </summary>
        // *** Start programmer edit section *** (Book.AverageCount CustomAttributes)

        // *** End programmer edit section *** (Book.AverageCount CustomAttributes)
        public virtual double AverageCount
        {
            get
            {
                // *** Start programmer edit section *** (Book.AverageCount Get start)

                // *** End programmer edit section *** (Book.AverageCount Get start)
                double result = this.fAverageCount;
                // *** Start programmer edit section *** (Book.AverageCount Get end)

                // *** End programmer edit section *** (Book.AverageCount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.AverageCount Set start)

                // *** End programmer edit section *** (Book.AverageCount Set start)
                this.fAverageCount = value;
                // *** Start programmer edit section *** (Book.AverageCount Set end)

                // *** End programmer edit section *** (Book.AverageCount Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BookE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookE", typeof(IIS.Club.Book));
                }
            }
            
            /// <summary>
            /// "BookL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookL", typeof(IIS.Club.Book));
                }
            }
        }
    }
}
